version: "3"
services:
  nginx:
    image: nginx:latest
    ports:
      - 8011:80
    volumes:
      - /home/nginx/html:/usr/share/nginx/html
      - /home/nginx/nginx.conf:/etc/nginx/nginx.conf
    privileged: true
  order:
    image: mail2future-service:latest
    build: .
    ports:
      - 8010: 8010
